---
driver:
  name: vagrant
  customize:
    memory: 5000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
#  - ["forwarded_port", {guest: 50070, host: 57777}]
#  - ["forwarded_port", {guest: 50075, host: 57775}]
#  - ["private_network", ip: "192.168.0.2"]


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: ubuntu-15.04
#  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[hops::rm]
      - recipe[hops::nm]
      - recipe[hops::jhs]
#      - recipe[hops::ps]
#      - recipe[hops::jn]

    attributes:
         apache_hadoop:
            hdfs:
               block_size: 8m
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            ps:
               private_ips: ["10.0.2.15"]
         ndb:
            user: mysql
            group: mysql
            DataMemory: "111"
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            enabled: "false"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"

